{% set name = "ford" %}
{% set version = "7.0.11" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d682372592de3414e10db6baee3e8bf52867006cf0b198f42b82ea735015128b

build:
  number: 0
  entry_points:
    - {{ name }} = {{ name }}:run
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - beautifulsoup4 >=4.5.1
    - jinja2 >=2.11
    - markdown >=3.4.0,<3.5
    - markdown-include >=0.7.0,<0.8
    - python-graphviz >=0.20.0,<0.21
    - python-markdown-math >=0.8,<0.9
    - pcpp >=1.30
    - pygments >=2.12,<2.13
    - python >={{ python_min }}
    - rich >=12.0.0,<13
    - tomli >=1.1.0
    - toposort >=1.7.0,<1.8
    - tqdm >=4.66.3

test:
  imports:
    - {{ name }}
  commands:
    - pip check
    - {{ name }} --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Fortran-FOSS-Programmers/ford
  summary: FORD, standing for FORtran Documenter, is an automatic documentation generator for modern Fortran programs.
  dev_url: https://github.com/Fortran-FOSS-Programmers/ford
  doc_url: https://forddocs.readthedocs.io
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
