{% set name = "ford" %}
{% set version = "6.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Fortran-FOSS-Programmers/ford/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5a264ee6a510bcec37f23e44d32d9c49d42bbf3a56b0fd0df246a2af242f80b9

build:
  number: 0
  entry_points:
    - {{ name }} = {{ name }}:run
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - beautifulsoup4 >=4.5.1
    - python-graphviz
    - jinja2 >=2.1
    - markdown
    - markdown-include >=0.5.1
    - md-environ
    - pygments
    - python >=3.8
    - toposort
    - tqdm

test:
  imports:
    - {{ name }}
  commands:
    - pip check
    - {{ name }} --help
  requires:
    - pip

about:
  home: https://github.com/Fortran-FOSS-Programmers/ford
  summary: FORD, standing for FORtran Documenter, is an automatic documentation generator for modern Fortran programs.
  dev_url: https://github.com/Fortran-FOSS-Programmers/ford
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
